### ISSUE TITLE
Is branch develop broken (?)

### ISSUE THREAD

**Issue by monacofj** [flossschool/pollex#14]
I'm not sure if I got it right, but as far I've understood the service is started from within pollex-flask... is that right?

If so, 
```
$ cd pollex-flask
$ make start
```
should bring up a container with the application entry and make it accessible at

`localhost:8080`

but, instead, I get a 404. I have not fully checked, but perhaps, Dockerfile is not copying the required files into the application image.

Would anyone please fix this so that we have at lease the landing paging being served?

**Comment by ET33** [comment]
Indeed. This issue is also resolved if we get #13 merged.

**Comment by ET33** [comment]
Fixed with #13
