### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by monacofj** [flossschool/pollex#15]
```
pollex/pollex-flask$ make start
make: *** No rule to make target 'instance/*', needed by 'pollex:dev'.  Stop.
```
Looks like `instance/*` is missing

**Comment by ET33** [comment]
The reason this happens is because `instance/` should not pushed to the repository as it might contain sensitive information (it's included in .gitignore).

As a workaround you can simply create this directory manually and a config.py file inside it.
I'll look into this later

**Comment by monacofj** [comment]
Updated `pollex-flask/Makefile` to create a local files as suggested.
Now `make' builds image successfully. 
I think merging #18 would do it.
