### ISSUE TITLE
Dockerize application

### ISSUE THREAD

**Issue by Vernalhav** [flossschool/pollex#25]

**Comment by Vernalhav** [comment]
Perhaps we could even add a Makefile in the project root that launches both containers for easier testing.

**Comment by monacofj** [comment]
Sure!
I've already noticed that it won't work smoothly in Ubuntu 18 due to outdated nodejs version.
One more reason to have a docker image with everything in in (based on ubuntu 19 at least).
Working on it.

**Comment by monacofj** [comment]
An initial attempt has been uploaded as branch `feature/dockerize` (it's WIP).
Help needed with angular setup (opening corresponding issues).

**Comment by monacofj** [comment]
Marking this issue as completed.
Subsequent development addressed in other issues (#32 )
