### ISSUE TITLE
Create poll list route

### ISSUE THREAD

**Issue by ET33** [flossschool/pollex#27]
We need a `/polls` route that responds all polls in which a user is participating.
It's expected to receive a GET request along with the user token (in the request header) and return an array of polls.
```
GET - /polls
Request:
    header: {
        "token": string
    }

Response:
    {
        "polls": [
            {
                "poll_id": int,
                "name": string,
                "poll_owner": string,
                "votes_number": int,
                "total_votes": int,
                "created_date": date
            },
            ...
        ]
    }
```

**Comment by andrefakhoury** [comment]
As the database isn't ready yet, we made the response template, so that the front-end can be developed. (I think this issue can be closed now)

**Comment by ET33** [comment]
Thanks!!
